name: BentoBox-Bank
main: world.bentobox.bank.BankPladdon
version: ${project.version}${build.number}
api-version: "1.16"

authors: [tastybento]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
